### ISSUE TITLE
Security issue with empty Redis password

### ISSUE THREAD

**Issue by Kintull** [ccarney16/pterodactyl-containers#77]
Leaving empty redis password is dangerous with attacks that can get access to `authorized_keys` file in `.ssh` directory.

We would need to these lines to `docker-compose.yml` cache service:

```
  cache:
    image: redis:alpine
    restart: always
    command: >
      --requirepass <YOUR_PASSWORD_HERE>
```

Also in `panel.env`:
```
REDIS_HOST=cache
REDIS_PORT=6379
REDIS_PASSWORD=<YOUR_PASSWORD_HERE>
```
